"""
flash.py — copy MicroPython source onto a USB-attached board.

Usage:
    flash creatures/cores3                   # copies main.py
    flash creatures/cores3 --port /dev/ttyACM0
    flash creatures/cores3 --wifi home       # also flashes wifi.py from .config/networks/home.toml
    flash wifi home                          # renders .config/networks/home.toml -> wifi.py only
    flash list-wifi                          # lists .config/networks/*.toml profiles

Without --port, looks for a single USB serial device and uses it.
Errors clearly when zero or multiple ports are found.
"""

import argparse
import os
import subprocess
import sys
import tempfile
import tomllib

from serial_device import usb_devices


NETWORKS_DIR = os.path.join(".config", "networks")


def _describe(d):
    return f"{d.device}  {d.manufacturer or '?'}  {d.product or '?'}"


def detect_port():
    devices = usb_devices()
    if not devices:
        raise SystemExit("flash: no USB serial device found — pass --port explicitly")
    if len(devices) > 1:
        lines = ["flash: multiple USB serial devices detected — pass --port to choose:"]
        for d in devices:
            lines.append(f"  {_describe(d)}")
        raise SystemExit("\n".join(lines))
    d = devices[0]
    print(f"flash: found USB device: {_describe(d)}")
    return d.device


# ── wifi.py rendering ──────────────────────────────────────────────────────

WIFI_PY_TEMPLATE = (
    "# Generated by `flash wifi {profile}`. Edit .config/networks/{profile}.toml, not this file.\n"
    "MODE = {mode!r}\n"
    "AP_SSID = {ap_ssid!r}\n"
    "AP_PASS = {ap_pass!r}\n"
    "AP_CHANNEL = {ap_channel}\n"
    "STA_SSID = {sta_ssid!r}\n"
    "STA_PASS = {sta_pass!r}\n"
    "SPINE_HOST_AP = {spine_host_ap!r}\n"
    "SPINE_HOST_STA = {spine_host_sta!r}\n"
    "SPINE_PORT = {spine_port}\n"
)

REQUIRED_KEYS = [
    "mode", "ap_ssid", "ap_pass", "ap_channel",
    "sta_ssid", "sta_pass",
    "spine_host_ap", "spine_host_sta", "spine_port",
]


def load_profile(name):
    path = os.path.join(NETWORKS_DIR, name + ".toml")
    if not os.path.isfile(path):
        raise SystemExit("flash: no profile at {}".format(path))
    with open(path, "rb") as f:
        cfg = tomllib.load(f)
    missing = [k for k in REQUIRED_KEYS if k not in cfg]
    if missing:
        raise SystemExit("flash: {} missing keys: {}".format(path, ", ".join(missing)))
    return cfg


def render_wifi_py(cfg, profile_name):
    return WIFI_PY_TEMPLATE.format(profile=profile_name, **cfg)


# ── Subcommands ────────────────────────────────────────────────────────────

def flash_creature(argv):
    parser = argparse.ArgumentParser(
        prog="flash", description="Flash main.py onto a board")
    parser.add_argument("creature_path",
                        help="Path to a directory containing main.py (e.g. creatures/cores3)")
    parser.add_argument("--port", default=None,
                        help="Serial port (auto-detected if omitted)")
    parser.add_argument("--wifi", default=None, metavar="PROFILE",
                        help="Also flash wifi.py rendered from .config/networks/<PROFILE>.toml before main.py")
    args = parser.parse_args(argv)

    main_py = os.path.join(args.creature_path, "main.py")
    if not os.path.isfile(main_py):
        parser.error("no main.py in {}".format(args.creature_path))

    wifi_tmp = None
    if args.wifi:
        cfg = load_profile(args.wifi)
        body = render_wifi_py(cfg, args.wifi)
        with tempfile.NamedTemporaryFile("w", suffix=".py", prefix="wifi_", delete=False) as tmp:
            tmp.write(body)
            wifi_tmp = tmp.name

    try:
        port = args.port or detect_port()
        if wifi_tmp:
            print("flash: wifi '{}' + {} -> {}".format(args.wifi, main_py, port))
        else:
            print("flash: {} -> {}".format(main_py, port))

        cmds = []
        if wifi_tmp:
            cmds.append(["mpremote", "connect", port, "cp", wifi_tmp, ":wifi.py"])
        cmds.append(["mpremote", "connect", port, "cp", main_py, ":main.py"])
        cmds.append(["mpremote", "connect", port, "reset"])
        for cmd in cmds:
            result = subprocess.run(cmd)
            if result.returncode != 0:
                sys.exit(result.returncode)
    finally:
        if wifi_tmp:
            os.unlink(wifi_tmp)


def flash_wifi(argv):
    parser = argparse.ArgumentParser(
        prog="flash wifi",
        description="Flash a wifi.py rendered from .config/networks/<profile>.toml")
    parser.add_argument("profile",
                        help="Profile name (file in .config/networks/, without .toml)")
    parser.add_argument("--port", default=None,
                        help="Serial port (auto-detected if omitted)")
    args = parser.parse_args(argv)

    cfg = load_profile(args.profile)
    body = render_wifi_py(cfg, args.profile)

    # Write to a tempfile so mpremote has a path to copy from.
    with tempfile.NamedTemporaryFile("w", suffix=".py", prefix="wifi_", delete=False) as tmp:
        tmp.write(body)
        tmp_path = tmp.name

    try:
        port = args.port or detect_port()
        print("flash wifi: profile '{}' -> {}".format(args.profile, port))
        cmds = [
            ["mpremote", "connect", port, "cp", tmp_path, ":wifi.py"],
            ["mpremote", "connect", port, "reset"],
        ]
        for cmd in cmds:
            result = subprocess.run(cmd)
            if result.returncode != 0:
                sys.exit(result.returncode)
    finally:
        os.unlink(tmp_path)


def list_wifi(argv):
    parser = argparse.ArgumentParser(
        prog="flash list-wifi",
        description="List network profiles in .config/networks/")
    parser.parse_args(argv)

    if not os.path.isdir(NETWORKS_DIR):
        print("no {}/ directory".format(NETWORKS_DIR))
        return
    profiles = sorted(f[:-5] for f in os.listdir(NETWORKS_DIR) if f.endswith(".toml"))
    if not profiles:
        print("no profiles in {}/".format(NETWORKS_DIR))
        return
    for p in profiles:
        print(p)


# ── Entry point ────────────────────────────────────────────────────────────

def main():
    argv = sys.argv[1:]
    if argv and argv[0] == "wifi":
        flash_wifi(argv[1:])
    elif argv and argv[0] == "list-wifi":
        list_wifi(argv[1:])
    else:
        flash_creature(argv)


if __name__ == "__main__":
    main()
