"""
flash.py — copy MicroPython source onto a USB-attached board.

Usage:
    flash creatures/cores3                   # full install: main.py + wifi.py + lib/
    flash creatures/cores3 --wifi guest      # full install, override wifi profile
    flash creatures/cores3 --no-wifi         # main.py + lib/ only
    flash creatures/cores3 --port /dev/ttyACM0
    flash wifi                               # wifi.py only, from config.toml
    flash wifi guest                         # wifi.py only, from named profile
    flash list-wifi                          # list .config/networks/*.toml profiles

When <creature>/lib/ exists, every .py/.mpy file under it is copied to /lib/
on the device, preserving subdirectories. MicroPython's default sys.path
includes /lib, so imports from main.py and instinct.py work without setup.

Wifi resolution (used by both `flash creatures/...` and `flash wifi`):
    1. CLI --wifi NAME / positional NAME → .config/networks/<NAME>.toml
    2. .config/config.toml [wifi]        → inline block
       .config/config.toml wifi = NAME   → shorthand, reads .config/networks/<NAME>.toml
    3. fallback (full install only): keep existing wifi.py on device, else error.

Without --port, looks for a single USB serial device and uses it.
Errors clearly when zero or multiple ports are found.
"""

import argparse
import os
import subprocess
import sys
import tempfile

from serial_device import usb_devices

from . import _config


def _describe(d):
    return f"{d.device}  {d.manufacturer or '?'}  {d.product or '?'}"


def detect_port():
    devices = usb_devices()
    if not devices:
        raise SystemExit("flash: no USB serial device found — pass --port explicitly")
    if len(devices) > 1:
        lines = ["flash: multiple USB serial devices detected — pass --port to choose:"]
        for d in devices:
            lines.append(f"  {_describe(d)}")
        raise SystemExit("\n".join(lines))
    d = devices[0]
    print(f"flash: found USB device: {_describe(d)}")
    return d.device


# ── wifi.py rendering ──────────────────────────────────────────────────────

WIFI_PY_TEMPLATE = (
    "# Generated by flash; source: {source}. Do not edit by hand.\n"
    "MODE = {mode!r}\n"
    "AP_SSID = {ap_ssid!r}\n"
    "AP_PASS = {ap_pass!r}\n"
    "AP_CHANNEL = {ap_channel}\n"
    "STA_SSID = {sta_ssid!r}\n"
    "STA_PASS = {sta_pass!r}\n"
    "SPINE_HOST_AP = {spine_host_ap!r}\n"
    "SPINE_HOST_STA = {spine_host_sta!r}\n"
    "SPINE_PORT = {spine_port}\n"
)

_REQUIRED_COMMON = ["mode", "ssid", "pass", "spine_host"]
_REQUIRED_AP_EXTRA = ["channel"]

# Old prefixed keys, kept around only so we can emit a useful migration error.
_LEGACY_KEYS = {
    "sta_ssid", "sta_pass", "spine_host_sta",
    "ap_ssid", "ap_pass", "ap_channel", "spine_host_ap",
}


def _check_required(cfg, label):
    legacy = sorted(set(cfg) & _LEGACY_KEYS)
    if legacy:
        raise SystemExit(
            "flash: {} uses legacy prefixed keys ({}). "
            "Schema is now mode-neutral: use ssid, pass, spine_host "
            "(and channel for ap). See .config/networks/example.toml."
            .format(label, ", ".join(legacy)))

    mode = cfg.get("mode")
    if not mode:
        raise SystemExit("flash: {} missing key: mode".format(label))
    if mode not in ("sta", "ap"):
        raise SystemExit(
            "flash: {} invalid mode {!r} (expected 'sta' or 'ap')".format(label, mode))
    required = list(_REQUIRED_COMMON)
    if mode == "ap":
        required += _REQUIRED_AP_EXTRA
    missing = [k for k in required if k not in cfg]
    if missing:
        raise SystemExit(
            "flash: {} missing keys: {}".format(label, ", ".join(missing)))


def load_wifi(name=None):
    """Resolve a wifi config the same way load_llm resolves an LLM.

    Returns (cfg, source) where:
        cfg    = dict with all REQUIRED_KEYS, or None when nothing configured.
        source = human-readable label for log output and the generated wifi.py
                 header (e.g. 'home', 'config.toml [wifi]'), or None.
    """
    if name:
        cfg = _config.load_profile("networks", name)
        _check_required(cfg, "profile " + name)
        return cfg, name

    toml = _config.load_config_toml()
    entry = toml.get("wifi")
    # Notation B — shorthand: wifi = "name"
    if isinstance(entry, str):
        cfg = _config.load_profile("networks", entry)
        _check_required(cfg, "profile " + entry)
        return cfg, entry
    # Notation A — inline [wifi] block
    if isinstance(entry, dict):
        _check_required(entry, "config.toml [wifi]")
        return entry, "config.toml [wifi]"
    return None, None


def render_wifi_py(cfg, source):
    # The device-side main.py imports flat STA_*/AP_* constants from wifi.py,
    # so we project the mode-neutral cfg into the right slots here. The
    # unused mode's fields get harmless defaults.
    mode = cfg["mode"]
    flat = {
        "mode": mode,
        "ap_ssid": "", "ap_pass": "", "ap_channel": 0,
        "sta_ssid": "", "sta_pass": "",
        "spine_host_ap": "", "spine_host_sta": "",
        "spine_port": cfg.get("spine_port", 8765),
    }
    if mode == "sta":
        flat["sta_ssid"] = cfg["ssid"]
        flat["sta_pass"] = cfg["pass"]
        flat["spine_host_sta"] = cfg["spine_host"]
    else:
        flat["ap_ssid"] = cfg["ssid"]
        flat["ap_pass"] = cfg["pass"]
        flat["ap_channel"] = cfg["channel"]
        flat["spine_host_ap"] = cfg["spine_host"]
    return WIFI_PY_TEMPLATE.format(source=source, **flat)


def _device_has_wifi_py(port):
    """Return True if wifi.py exists on the device. ~200-400ms over USB."""
    result = subprocess.run(
        ["mpremote", "connect", port, "ls"],
        capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit("flash: could not ls device: " + result.stderr.strip())
    for line in result.stdout.splitlines():
        token = line.strip().split()[-1] if line.strip() else ""
        if token == "wifi.py":
            return True
    return False


_NO_WIFI_HINT = (
    "flash: no wifi configured and device has no wifi.py — "
    "set [wifi] / wifi=\"...\" in .config/config.toml, pass --wifi NAME, "
    "or use --no-wifi to install main.py only"
)


# ── lib/ flashing ──────────────────────────────────────────────────────────

def _collect_lib_files(lib_dir):
    """Return [(local_path, remote_path), ...] for every .py/.mpy under lib_dir.

    Subdirectories are preserved. Non-Python files are skipped (the convention
    is 'device-side Python only' — pack assets into the firmware some other way
    if you need them).

    Remote paths use no leading slash (e.g. 'lib/vl53l0x.py'). mpremote 1.27's
    `mkdir :/lib` silently no-ops but `mkdir :lib` works; use the working form.
    """
    out = []
    for root, _, names in os.walk(lib_dir):
        for n in sorted(names):
            if not n.endswith((".py", ".mpy")):
                continue
            local = os.path.join(root, n)
            rel = os.path.relpath(local, lib_dir).replace(os.sep, "/")
            out.append((local, "lib/" + rel))
    return out


def _ensure_remote_dirs(port, files):
    """mkdir every unique parent directory on the device.

    Ignores "File exists" (mpremote exits 1 in that case but the desired state
    is already reached). Surfaces other failures as warnings so we don't fail
    silently if e.g. the device went away.
    """
    dirs = sorted({os.path.dirname(remote) for _, remote in files})
    for d in dirs:
        result = subprocess.run(
            ["mpremote", "connect", port, "mkdir", ":" + d],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            combined = (result.stderr + result.stdout).lower()
            if "exists" not in combined:
                print("flash: warning: mkdir :{} failed: {}".format(
                    d, (result.stderr + result.stdout).strip()))


# ── Subcommands ────────────────────────────────────────────────────────────

def flash_creature(args):
    main_py = os.path.join(args.creature_path, "main.py")
    if not os.path.isfile(main_py):
        raise SystemExit("flash: no main.py in {}".format(args.creature_path))

    port = args.port or detect_port()

    wifi_tmp = None
    wifi_action = None    # "write", "keep", "skipped"
    wifi_src = None

    if args.no_wifi:
        wifi_action = "skipped"
    else:
        cfg, src = load_wifi(args.wifi)
        if cfg is not None:
            wifi_action = "write"
            wifi_src = src if not args.wifi else "--wifi " + args.wifi
            body = render_wifi_py(cfg, src)
            with tempfile.NamedTemporaryFile("w", suffix=".py", prefix="wifi_", delete=False) as tmp:
                tmp.write(body)
                wifi_tmp = tmp.name
        else:
            if _device_has_wifi_py(port):
                wifi_action = "keep"
            else:
                raise SystemExit(_NO_WIFI_HINT)

    if wifi_action == "write":
        print("flash: wifi from {}".format(wifi_src))
    elif wifi_action == "keep":
        print("flash: wifi: keeping existing on device")
    else:
        print("flash: wifi: skipped (--no-wifi)")
    print("flash: main from {}".format(main_py))
    print("flash: -> {}".format(port))

    # Optional device-side library files: <creature>/lib/*.py go to /lib/ on
    # the device, preserving subdirectories. MicroPython has /lib on sys.path
    # by default so `import vl53l0x` works from main.py and instinct.py alike.
    lib_dir = os.path.join(args.creature_path, "lib")
    lib_files = _collect_lib_files(lib_dir) if os.path.isdir(lib_dir) else []
    if lib_files:
        print("flash: lib from {} ({} files)".format(lib_dir, len(lib_files)))

    try:
        cmds = []
        if wifi_action == "write":
            cmds.append((["mpremote", "connect", port, "cp", wifi_tmp, ":wifi.py"], "copied wifi.py"))
        cmds.append((["mpremote", "connect", port, "cp", main_py, ":main.py"], "copied main.py"))

        if lib_files:
            _ensure_remote_dirs(port, lib_files)
            for local, remote in lib_files:
                cmds.append(
                    (["mpremote", "connect", port, "cp", local, ":" + remote],
                     "copied {} -> {}".format(os.path.relpath(local), remote))
                )

        cmds.append((["mpremote", "connect", port, "reset"], "reset"))
        for cmd, msg in cmds:
            result = subprocess.run(cmd)
            if result.returncode != 0:
                sys.exit(result.returncode)
            print("flash: " + msg)
    finally:
        if wifi_tmp:
            os.unlink(wifi_tmp)


def flash_wifi(args):
    cfg, src = load_wifi(args.profile)
    if cfg is None:
        raise SystemExit(
            "flash wifi: no profile given and no [wifi] / wifi=\"...\" in .config/config.toml")
    body = render_wifi_py(cfg, src)

    with tempfile.NamedTemporaryFile("w", suffix=".py", prefix="wifi_", delete=False) as tmp:
        tmp.write(body)
        tmp_path = tmp.name

    try:
        port = args.port or detect_port()
        print("flash wifi: from {} -> {}".format(src, port))
        cmds = [
            (["mpremote", "connect", port, "cp", tmp_path, ":wifi.py"], "copied wifi.py"),
            (["mpremote", "connect", port, "reset"], "reset"),
        ]
        for cmd, msg in cmds:
            result = subprocess.run(cmd)
            if result.returncode != 0:
                sys.exit(result.returncode)
            print("flash wifi: " + msg)
    finally:
        os.unlink(tmp_path)


def list_wifi(args):
    networks_dir = os.path.join(".config", "networks")
    if not os.path.isdir(networks_dir):
        print("no {}/ directory".format(networks_dir))
        return
    profiles = sorted(f[:-5] for f in os.listdir(networks_dir) if f.endswith(".toml"))
    if not profiles:
        print("no profiles in {}/".format(networks_dir))
        return
    for p in profiles:
        print(p)


# ── Entry point ────────────────────────────────────────────────────────────

def _build_parser():
    parser = argparse.ArgumentParser(
        prog="flash",
        description="Flash MicroPython files onto an M5Stack board.",
    )
    sub = parser.add_subparsers(dest="cmd", metavar="COMMAND")

    p_creature = sub.add_parser(
        "creature",
        help="Flash main.py (+ wifi.py) onto a board",
        description="Flash main.py and (unless --no-wifi) wifi.py from a creature directory.",
    )
    p_creature.add_argument("creature_path",
        help="Path to a directory containing main.py (e.g. creatures/cores3)")
    p_creature.add_argument("--port", default=None,
        help="Serial port (auto-detected if omitted)")
    wifi_group = p_creature.add_mutually_exclusive_group()
    wifi_group.add_argument("--wifi", default=None, metavar="PROFILE",
        help="Override wifi profile from .config/networks/<PROFILE>.toml")
    wifi_group.add_argument("--no-wifi", action="store_true",
        help="Skip wifi flash (write main.py only)")
    p_creature.set_defaults(func=flash_creature)

    p_wifi = sub.add_parser(
        "wifi",
        help="Flash wifi.py only (no main.py)",
        description="Write wifi.py to the device from a named profile or .config/config.toml.",
    )
    p_wifi.add_argument("profile", nargs="?", default=None,
        help="Profile name (omit to use .config/config.toml)")
    p_wifi.add_argument("--port", default=None,
        help="Serial port (auto-detected if omitted)")
    p_wifi.set_defaults(func=flash_wifi)

    p_list = sub.add_parser(
        "list-wifi",
        help="List network profiles in .config/networks/",
        description="List network profiles found in .config/networks/.",
    )
    p_list.set_defaults(func=list_wifi)

    return parser


_KNOWN_COMMANDS = {"creature", "wifi", "list-wifi"}


def main():
    argv = sys.argv[1:]

    # Back-compat shortcut: `flash <path>` -> `flash creature <path>` when the
    # first arg is neither a known subcommand nor a flag. Keeps existing muscle
    # memory working after the subparser refactor.
    if argv and argv[0] not in _KNOWN_COMMANDS and not argv[0].startswith("-"):
        argv = ["creature"] + argv

    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.cmd is None:
        parser.print_help()
        sys.exit(2)

    args.func(args)


if __name__ == "__main__":
    main()
