[project]
name = "instinct-and-soul"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.39.0",
    "esptool>=5.2.0",
    "mpremote>=1.27.0",
    "rich>=14.3.3",
    "serial-device",
    "textual>=8.0.2",
    "websockets>=16.0",
]

[project.scripts]
spine = "instinct_and_soul.spine:main"
tune = "instinct_and_soul.tune:main"
flash = "instinct_and_soul.flash:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
serial-device = { git = "https://github.com/daan/serial_device" }
